### ISSUE TITLE
Improvement: Writing Chunks

### ISSUE THREAD

**Issue by ghost** [hldr4/shaka-packager#2]
At this moment it will first write to a temporary file and after that it will copy the file to the desired output file.

Two ways to improve this which will make it much faster: 
- Write the decrypted chunks directly to the output file.
 - Rename the temporary file to the desired output filename.

**Comment by hldr4** [comment]
What you are describing only applies to the original shaka version, since this is forked from truedread's mod it does not have this limitation, he already added the second option you propose a while ago. See [this](https://github.com/shaka-project/shaka-packager/commit/7766766514c19e4c7fa88718ae40728dc3457da9#diff-dab12eb243a66f5664654032317ccec47bd2ca591d22d3e34fab6a5e890d9d02) diff
